# Vortex 样本外预测配置示例
# 说明：该配置假设训练阶段已保存模型与预处理器，本流程仅负责加载模型并生成预测结果。

data_sources:
  factor_path: "./data/selected_factors_kline3.parquet"  # 必填：因子数据 Parquet 文件路径，必须存在。
  ohlc_path: "./data/ohlc"  # 必填：行情 CSV 文件所在目录，需包含至少一个 csv。
  date_column: "交易日期"  # 选填：日期列名称，如不填则使用默认值 "交易日期"。
  asset_column: "股票代码"  # 选填：资产代码列名称，默认 "股票代码"。
  close_column: "收盘价_复权"  # 选填：收盘价列名称，用于计算收益，默认 "收盘价_复权"。
  target_return:
    period: 5  # 必填：持有期长度（交易日数），决定前瞻收益窗口。
    type: "forward_return"  # 必填：目标类型，目前仅支持 forward_return。
    entry_price_column: "开盘价_复权"  # 选填：开仓价列名，缺省时采用 close_column。
    exit_price_column: "开盘价_复权"  # 选填：平仓价列名，缺省时采用 close_column。
    entry_shift: 1  # 选填：建仓相对于当前行的偏移，默认 0 表示当日建仓。
    exit_shift: null  # 选填：平仓相对于当前行的偏移，缺省时等于 entry_shift + period。
    standardization:
      method: "none"  # 选填：目标标准化方法，可选 none/rank。
      params:
        center: false  # 选填：是否在秩标准化后进行居中处理。

dataset_manager:
  walk_forward:
    start_date: "2011-01-01"  # 必填：回测起始日期。
    end_date: "2025-09-30"  # 必填：回测结束日期。
    train_window_type: "fixed"  # 必填：训练窗口类型，可选 expanding / fixed。
    train_length: 756  # 必填：训练集最小包含的交易日数量。
    test_length: 21  # 必填：每个测试窗口的交易日数量。
    step_length: 21  # 必填：滑窗步长，控制下一次滚动的起始点。
    embargo_length: 5  # 必填：禁区长度，防止训练集与测试集信息泄漏。

feature_selector:
  pipeline:
#    - method: "pca"  # 必填：步骤使用的算法名称，此处示例为主成分分析。
#      params:
#        n_components: 20  # 选填：主成分数量，默认 10；较大值会保留更多信息。
#    - method: "rank_ic_filter"  # 第二步通过 Rank IC 筛选效果最好的因子。
#      params:
#        top_k: 100  # 选填：保留的因子数量上限，未设置时不限制数量。
#        min_icir: 0.5  # 选填：ICIR 阈值，低于该值的因子将被剔除。
    - method: "default"
      params:
        n: -1

prediction:
  model_name: "lightgbm_ranker"  # 必填：训练阶段使用的模型名称，用于命名输出列。
  artifacts_path: "./artifacts/models4"  # 必填：保存模型与预处理器的目录。
  filename_template: "{model_name}_{train_end_date}"  # 必填：与训练时一致的文件命名模板。
  output_path: "./artifacts/predictions/factor_lightgbm4.pkl"  # 选填：预测结果输出路径，默认 ./artifacts/predictions.pkl。

# 绩效评估配置
# 必填：决定绩效分析输出的指标维度及假设。
performance_analyzer:
  quantiles: 10  # 选填：分组数量，默认为 5。
  risk_free_rate: 0.02  # 选填：无风险利率年化值，用于计算夏普比率。
  group_by_columns: null  # 选填：指定额外分组列，缺省表示仅按日期聚合。
