# Vortex 样本外预测配置示例
# 说明：该配置假设训练阶段已保存模型与预处理器，本流程仅负责加载模型并生成预测结果。

data_sources:
  factor_path: "./data/factors/example_factors.parquet"  # 必填：原始因子数据 Parquet 文件。
  ohlc_path: "./data/ohlc"  # 必填：行情数据目录，用于补充缺失价格字段。
  target_return:
    period: 5  # 与训练阶段保持一致的目标定义。
    type: "forward_return"
    standardization:
      method: "rank"
      params:
        center: true

dataset_manager:
  walk_forward:
    start_date: "2018-01-01"
    end_date: "2020-12-31"
    train_window_type: "expanding"
    train_length: 252
    test_length: 21
    step_length: 21
    embargo_length: 5

feature_selector:
  pipeline:
    - method: "pca"
      params:
        n_components: 20
    - method: "rank_ic_filter"
      params:
        top_k: 100
        min_icir: 0.5

prediction:
  model_name: "lightgbm"  # 必填：训练阶段使用的模型名称，用于命名输出列。
  artifacts_path: "./artifacts/models"  # 必填：保存模型与预处理器的目录。
  filename_template: "{model_name}_{train_end_date}"  # 必填：与训练时一致的文件命名模板。
  output_path: "./artifacts/predictions/factor_lightgbm.pkl"  # 选填：预测结果输出路径，默认 ./artifacts/predictions.pkl。
